version: '3.9'
services:
  content:
    build: .
    networks: 
      - lab
    image: shell-case-statements-content-image
    volumes:
      - src-volume:/root/lab/src
  workspace:
    depends_on:
      - content
    networks: 
      - lab
    image: wetty-linuxproject
    ports: 
      - "3000:3000"
    volumes:
      - src-volume:/home/project

volumes:
  src-volume:

networks:
  lab: