version: '3.9'
services:
  content:
    build: .
    networks: 
      - lab
    image: yaml-python-content
    volumes:
      - src-volume:/root/lab/src
  workspace:
    depends_on:
      - content
    networks: 
      - lab
    image: yaml-python # local_image|421805900968.dkr.ecr.us-east-2.amazonaws.com/cloudacademy/labs-workspace/remote_image
    ports: 
      - "3000:3000"
    volumes:
      - src-volume:/home/project

volumes:
  src-volume:

networks:
  lab: